INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (1, 'Чемпионат Европы 2016', 1, '2016-06-10', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (2, 'updated964000', 2, '2018-06-10', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (3, '808373', 2, '2018-06-10', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (4, '857167', 2, '2018-06-10', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (5, '529727', 2, '2018-06-10', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (6, '964626', 2, '2018-06-10', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (7, 'Тестовый турнир12', 39, '2020-08-12', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (8, 'Турнирчик', 31, '2019-12-12', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (9, 'Тестовый турнир13', 32, '2018-10-10', 1);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (10, 'New tournament 15', 38, '2020-08-12', 1);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (11, 'New Tournament 16', 17, '2020-10-10', 1);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (12, 'тур12', 22, '2020-08-12', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (13, '729468', 2, '2017-11-29', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (14, '401983', 2, '2017-11-30', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (15, 'Турнир в Японии', 26, '2018-12-10', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (16, 'Турнир в Японии 2', 21, '2018-12-10', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (17, 'Турнир в Японии 3', 21, '2018-12-12', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (18, 'Турнир в Японии 4', 21, '2018-12-10', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (19, 'Турнир в Японии 5', 21, '2018-12-12', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (20, 'Турнир в Японии 7', 21, '2018-12-12', 2);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (21, 'Новый турнир 20', 20, '2017-12-10', 1);
INSERT INTO myforecasts.tournaments (id, tournament_name, team_organizer_id, tournament_start_date, tournament_state_id) VALUES (22, 'Турнир Минск', 38, '2017-12-22', 2);